# Stack Archote mutada para Coolify / Dokploy
# FQDNs Mapeados no Traefik/Coolify:
# - n8n: archote-ipaas.inovage.digital
# - n8n_ppa: ppa-archote-ipaas.inovage.digital
# - rabbitmq: archote-mq.inovage.digital
# - pgadmin: archote-pgadmin.inovage.digital

services:
  postgres:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_USER: "n8n"
      POSTGRES_PASSWORD: "${DB_POSTGRESDB_PASSWORD:-n8n_password}"
      POSTGRES_DB: "n8n"
    volumes:
      - archote_postgres_data:/var/lib/postgresql/data

  #pgadmin:
  #  image: dpage/pgadmin4
  #  environment:
  #   PGADMIN_DEFAULT_EMAIL: "marco.martins@inovage.com.br"
  #    PGADMIN_DEFAULT_PASSWORD: "${N8N_BASIC_AUTH_PASSWORD}"
  #    PGADMIN_DISABLE_EMAIL_CHECK: "True"
  #  depends_on:
  #    - postgres

  # Archote Industria
  n8n:
    image: makarioszen/i9dig-n8n
    ports:
      - 5678:5678
    environment:
      NODE_ENV: production
      N8N_USER_FOLDER: /data
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_HOST: coolify-archote-n8n.inovage.digital
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://coolify-archote-n8n.inovage.digital/
      GENERIC_TIMEZONE: America/Sao_Paulo
      NODE_FUNCTION_ALLOW_EXTERNAL: odbc,qs
      NODE_FUNCTION_ALLOW_BUILTIN: fs
      N8N_REDIS_HOST: redis
      N8N_REDIS_PORT: 6379
      N8N_QUEUE_MODE: "true"
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD:-n8n_password}
      EXECUTIONS_PROCESS: main
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: none
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - archote_n8n_data:/data

  redis:
    image: "redis:6-alpine"

  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    labels:
      - "coolify.fqdn=https://coolify-archote-mq.inovage.digital"
    environment:
      RABBITMQ_DEFAULT_USER: ${N8N_BASIC_AUTH_USER}
      RABBITMQ_DEFAULT_PASS: ${N8N_BASIC_AUTH_PASSWORD}
    volumes:
      - archote_rabbitmq_data:/var/lib/rabbitmq

  # PPA Distribuidora
  redis_ppa:
    image: "redis:6-alpine"

  n8n_ppa:
    image: makarioszen/i9dig-n8n
    ports:
      - 5679:5678
    environment:
      NODE_ENV: production
      N8N_USER_FOLDER: /data
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_HOST: coolify-archote-ppa.inovage.digital
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://coolify-archote-ppa.inovage.digital/
      GENERIC_TIMEZONE: America/Sao_Paulo
      NODE_FUNCTION_ALLOW_EXTERNAL: odbc,qs
      NODE_FUNCTION_ALLOW_BUILTIN: fs
      N8N_REDIS_HOST: redis_ppa
      N8N_REDIS_PORT: 6379
      N8N_QUEUE_MODE: "true"
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ppa_n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD:-n8n_password}
      EXECUTIONS_PROCESS: main
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: none
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
    depends_on:
      - postgres
      - redis_ppa
    volumes:
      - archote_n8n_data_ppa:/data

volumes:
  archote_n8n_data:
  archote_postgres_data:
  archote_rabbitmq_data:
  archote_n8n_data_ppa:
